---
- name: "Chocolatey Install / Remove Packages"
  hosts: all
  become: yes
  #become_method: runas
  #become_user: eng\mpeadmin
  #become_flags: logon_type=interactive logon_flags=with_profile

  vars:
    feature: stopOnFirstPackageFailure
    state: enabled

  tasks:
    - name: install or remove packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ choco_packages }}"
        state: "{{ state }}"
        source: https://HYSDWV-00CHO001.eng.homebox.com:8443/repository/ChocolateyInternal/

    - name: Disable Community Repo
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: disabled

    - name: Displays the configured chocolately sources
      debug:
        var: ansible_chocolatey.sources